### ISSUE TITLE
KeyError: 'little'

### ISSUE THREAD

**Issue by varunchandak** [frehder/mbox2eml#1]
```
Traceback (most recent call last):
  File "/Users/this/that/Takeout/Mail/other/mbox2eml.py", line 129, in <module>
    month_int = month_abbr_to_int[line_parts[3]]
KeyError: 'little'
```

**Comment by varunchandak** [comment]
also,

```
python mbox2eml.py --file SOMETHING.mbox --output .
Estimated amount of emails to create: 10953
Start process? [y|n]
```

**Comment by frehder** [comment]
Thank you for posting this issue. I will try to reproduce and fix it.

Which python version are you using?

**Comment by varunchandak** [comment]
Python 3.9.12

**Comment by frehder** [comment]
I fixed some minor errors regarding Python v3.
Would you please pull the changes and try again?

**Comment by varunchandak** [comment]
I forgot to mention, I did do the `2to3` to the python to make it version 3 compatible, the error occurred was after this change.
